
services:
  mongo:
    image: mongo:5
    restart: always
    volumes:
      - ./data-db/:/data/db/

  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      DATABASE_PATH: "mongodb://mongo:27017"
      NODE_OPTIONS: "--openssl-legacy-provider"
      ENABLE_LOCAL_FLAGS: "1"
